language: python
python:
  - "3.2"
#  - "3.3"

before_script:
  # Setup Mysql 5.6 (source: https://github.com/travis-ci/travis-ci/issues/1986)
  - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
  - "sudo apt-get autoremove"
  - "sudo apt-get install libaio1"
  - "wget -O mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
  - "sudo dpkg -i mysql-5.6.14.deb"
  - "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
  - "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
  - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
  - "sudo /etc/init.d/mysql.server start"
  - "sudo mysql_upgrade"
  - "sudo /etc/init.d/mysql.server stop"
  - "echo -e '[mysqld]\\ngtid_mode=ON\\nenforce_gtid_consistency\\nbinlog_format=ROW\\nlog_bin=/tmp/tests-mysql56.log\\nlog_slave_updates' | sudo tee /etc/mysql/conf.d/gtid.cnf"
  - "sudo /etc/init.d/mysql.server start||/bin/true"
  - "sudo tail -1000 /var/log/syslog"
  #- "cat /etc/mysql/my.cnf"
  #- "sudo ls /var/ramfs/mysql/"
  #- "sudo cat /var/ramfs/mysql/*.err"
  - mysql --version
  - mysql -e "SELECT VERSION();"

# Fail build
script: /bin/false


