language: python
python:
  - "3.2"
#  - "3.3"

cache:
  directories:
    - .mysql

before_script:
  - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
  - "sudo apt-get autoremove"

  - "echo deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6 | sudo tee /etc/apt/sources.list.d/mysql.list"
  - "sudo apt-key add .mysql/dev.mysql.com.gpg.key"
  - "sudo apt-get update"
  - "sudo env DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::='--force-confold' -q -y mysql-server"

  - "sudo rm -rf /var/ramfs/mysql/"
  - "sudo mkdir /var/ramfs/mysql/"
  - "sudo chown mysql: /var/ramfs/mysql/"

  #- "mkdir -p .mysql"
  #- "test -f .mysql/mysql-5.6.14.deb || wget -O .mysql/mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
  #- "sudo dpkg -i .mysql/mysql-5.6.14.deb"
  #- "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"

  - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"

  - "cat /etc/mysql/my.cnf"
  - "mysql_install_db --defaults-file=/etc/mysql/my.cnf --basedir=/usr --datadir=/var/ramfs/mysql"

  - "sudo /etc/init.d/mysql start"
  - "sudo tail -1000 /var/log/syslog"
  - "sudo /etc/init.d/mysql stop"
  - "echo -e '[mysqld]\\ngtid_mode=ON\\nenforce_gtid_consistency\\nbinlog_format=ROW\\nlog_bin=/tmp/tests-mysql56.log\\nlog_slave_updates' | sudo tee /etc/mysql/conf.d/gtid.cnf"
  - "sudo /etc/init.d/mysql start"

  #- "sudo tail -1000 /var/log/syslog"
  ##- "cat /etc/mysql/my.cnf"
  ##- "sudo ls /var/ramfs/mysql/"
  ##- "sudo cat /var/ramfs/mysql/*.err"

  - mysql --version
  - mysql -e "SELECT VERSION();"

# Fail build
script: /bin/false
#script: /bin/true


